# Generated by Django 2.1.2 on 2018-10-12 20:33

from django.db import migrations, models


TARGET_APP = 'auth'


class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        # overriding application operated upon
        super(Migration, self).__init__(name, TARGET_APP)

    # specify what original migration file it replaces
    # or leave migration loader confused about unapplied migration
    replaces = ((TARGET_APP, __module__.rsplit('.', 1)[-1]),)

    dependencies = [
        ('slcsd_cms', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Site Title'),
        ),
    ]

