# Generated by Django 2.1.2 on 2018-11-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slcsd_cms', '0003_site_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='development_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='slcsd_cms.Domain'),
        ),
        migrations.AddField(
            model_name='site',
            name='production_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='slcsd_cms.Domain'),
        ),
        migrations.AddField(
            model_name='site',
            name='testing_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='slcsd_cms.Domain'),
        ),
    ]
