# Generated by Django 2.1.2 on 2018-12-03 23:11

from django.db import migrations, models
import uuid

TARGET_APP = 'auth'


def generate_uuid(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group in Group.objects.all():
        group.uuid = uuid.uuid4()
        group.save()


class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        # overriding application operated upon
        super(Migration, self).__init__(name, TARGET_APP)

    # specify what original migration file it replaces
    # or leave migration loader confused about unapplied migration
    replaces = ((TARGET_APP, __module__.rsplit('.', 1)[-1]),)

    dependencies = [
        ('slcsd_cms', '0004_change_site_canonicals_to_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            generate_uuid,
        ),
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
