# Generated by Django 2.1.2 on 2018-12-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slcsd_cms', '0005_group_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='group',
        ),
    ]
