# Generated by Django 2.1.2 on 2018-12-04 17:18

from django.db import migrations


def create_group(self, Group):
    group_type = 'Publishers' if not self.management else 'Managers'
    group_title = '{0} {1}'.format(self.title, group_type)
    group_description = '{0} group for site: {1}'.format(group_type, self.title)
    self.group, created = Group.objects.get_or_create(
        name='{0}'.format(self.pk),
        defaults={
            'title': group_title,
            'description': group_description
        }
    )
    if not created:
        original_group = {
            'title': self.group.title,
            'description': self.group.description,
        }
        new_group = {
            'title': group_title,
            'description': group_description,
        }
        if original_group != new_group:
            self.group.title = group_title
            self.group.description = group_description
            self.group.save()
    return self.group


def save_site(apps, schema_editor):
    Site = apps.get_model('slcsd_cms', 'Site')
    Group = apps.get_model('auth', 'Group')
    for site in Site.objects.all():
        site.group = create_group(site, Group)
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('slcsd_cms', '0007_site_group'),
    ]

    operations = [
        migrations.RunPython(save_site),
    ]
