# Generated by Django 2.1.2 on 2018-12-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slcsd_cms', '0008_set_site_group_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='development_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slcsd_cms.Domain'),
        ),
        migrations.AlterField(
            model_name='site',
            name='production_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slcsd_cms.Domain'),
        ),
        migrations.AlterField(
            model_name='site',
            name='testing_canonical',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slcsd_cms.Domain'),
        ),
    ]
