# Generated by Django 2.1.2 on 2018-12-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slcsd_cms', '0009_site_canonicals_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('delete_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.TextField(null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('encoding', models.CharField(blank=True, max_length=255, null=True)),
                ('request_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request_content_length', models.BigIntegerField(blank=True, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('ajax', models.BooleanField(default=False)),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('accept', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cache_control', models.CharField(blank=True, max_length=255, null=True)),
                ('accept_language', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.CharField(blank=True, max_length=255, null=True)),
                ('accept_encoding', models.CharField(blank=True, max_length=255, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('remaining_request_headers', models.TextField(blank=True, null=True)),
                ('response_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('response_content_length', models.BigIntegerField(blank=True, null=True)),
                ('response_vary', models.CharField(blank=True, max_length=255, null=True)),
                ('response_x_frame_options', models.TextField(blank=True, null=True)),
                ('remaining_response_headers', models.TextField(blank=True, null=True)),
                ('processing_time', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=40, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_create_user', to=settings.AUTH_USER_MODEL)),
                ('delete_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_delete_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='slcsd_cms.Site')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_update_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('create_date',),
                'get_latest_by': 'create_date',
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
    ]
